# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.13-slim

WORKDIR /app

# Copy dependency definitions
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN pip install --no-cache-dir .

# Copy application source
COPY . .

# Default: run MCP server via mcp CLI
CMD ["mcp", "run", "main.py"]
